[tool.poetry]
name = "parking-lot"
version = "0.1.0"
description = ""
authors = ["Felipe Sanchez <f.sanxz@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
